### ISSUE TITLE
Drama paragraph indentation

### ISSUE THREAD

**Issue by robinwhittleton** [standardebooks/manual#16]
In the drama CSS we use:

```css
[epub|type~="z3998:drama"] td p{
        text-indent: 0;
}
```

With run-on monologues this has the effect of removing all paragraph separation. Should we add a first child pseudoclass?

```css
[epub|type~="z3998:drama"] td p:first-child{
        text-indent: 0;
}
```
